null===window.localStorage.getItem("bookmarks")&&(window.localStorage.setItem("bookmarks",JSON.stringify([])),bookmarks=window.localStorage.getItem("bookmarks"));var localBookmarks=JSON.parse(window.localStorage.getItem("bookmarks")),bookmarksList=document.querySelector(".bookmarks-list"),form={};form.url=document.querySelector(".url-input");form.submitButton=document.querySelector(".url-submit");form.submitButton.addEventListener("click",addBookmark);var filterInput=document.querySelector(".filter-input");
filterInput.addEventListener("input",filterBookmarks);retreiveBookmarks(1);function retreiveBookmarks(a,b){b=void 0===b?localBookmarks:b;var d=1===a?1:a.target.value;for(var c=20*(d-1),e=c+b.slice(c,c+20).length;bookmarksList.hasChildNodes();)bookmarksList.removeChild(bookmarksList.lastChild);for(;c<e;c++)buildListElement(c,b[c]);addPageNumbers(d,b)}
function buildListElement(a,b){var d=b.url,c=document.createElement("li"),e=b.tags;newDiv=document.createElement("div");newDiv.className="bookmarks-list-item";newDiv.style.backgroundColor="hsl("+(200-5*a).toString()+", 30%, 80%)";newAnchor=document.createElement("a");newAnchor.setAttribute("href",d);"";newAnchor.setAttribute("target","_blank");newAnchor.innerHTML=d;newDiv.appendChild(newAnchor);c.appendChild(newDiv);bookmarksList.appendChild(c);newDeleteButton=document.createElement("button");newDeleteButton.className=
"delete-button ";newDeleteButton.id=a;newDeleteButton.innerHTML="Remove";newDeleteButton.addEventListener("click",removeBookmark);newDiv.appendChild(newDeleteButton);newEditButton=document.createElement("button");newEditButton.className="list-button";newEditButton.id=a;newEditButton.innerHTML="Edit";newEditButton.addEventListener("click",editBookmark);newDiv.appendChild(newEditButton);""!==e[0]&&(d=generateTagButtons(a,b),0!==d.length&&newDiv.appendChild(d))}
function addBookmark(a){a.preventDefault();var b=form.url.value;a=urlValidator(b);console.log(a);urlValidator(b)[0]?(b={},b.url=a[1],b.tags=[],b.time=new Date,localBookmarks.push(b),window.localStorage.setItem("bookmarks",JSON.stringify(localBookmarks)),window.location.href="results.html"):alert("Please enter a valid url")}function removeBookmark(a){localBookmarks.splice(a.target.id,1);window.localStorage.setItem("bookmarks",JSON.stringify(localBookmarks));location.reload()}
function editBookmark(a){var b=a.target.id;console.log(b);form.url.value=a.target.parentElement.children[0].innerHTML;form.url.focus();form.submitButton.innerHTML="update";form.submitButton.removeEventListener("click",addBookmark);form.submitButton.addEventListener("click",function(a){a.preventDefault();localBookmarks[b].url=form.url.value;console.log(localBookmarks);window.localStorage.setItem("bookmarks",JSON.stringify(localBookmarks));location.reload()});a=document.createElement("button");a.className=
"url-submit";a.innerHTML="cancel";a.addEventListener("click",function(){location.reload()});document.querySelector(".url-form-container").appendChild(a)}function urlValidator(a){/^http[s]?:\/\//.test(a)||(a="https://"+a);return[/^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i.test(a),a]}
function addPageNumbers(a,b){for(var d=document.querySelector(".page-numbers");d.hasChildNodes();)d.removeChild(d.lastChild);numPages=Math.ceil(b.length/20);for(var c=1;c<=numPages;c++)pageButton=document.createElement("button"),pageButton.className="page-button",pageButton.innerHTML=c,pageButton.setAttribute("value",c),c==a&&(pageButton.style.borderWidth="5px"),pageButton.addEventListener("click",retreiveBookmarks),d.appendChild(pageButton)}
function filterBookmarks(){tag=document.querySelector(".filter-input").value.toLowerCase();console.log(tag);bookmarks=""===tag?localBookmarks:localBookmarks.filter(function(a){tags=a.tags;return 0===tags.length?!1:tags.includes(tag)});retreiveBookmarks(1,bookmarks)}
function generateTagButtons(a,b){tags=b.tags;var d=document.createElement("div");d.className="tag-container";for(var c=document.querySelector(".filter-input"),e=0;e<tags.length;e++){var f=document.createElement("button");f.className="tag-button";f.innerHTML=tags[e];f.setAttribute("value",tags[e]);f.addEventListener("click",function(a){c.setAttribute("value",a.target.value);filterBookmarks(c.value)});d.appendChild(f)}return d};
